# Generated by Django 5.2.3 on 2025-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('ECO', 'Económica'), ('PRE', 'Premium'), ('BUS', 'Ejecutiva'), ('FIR', 'Primera Clase')], max_length=100),
        ),
    ]
