# Generated by Django 5.2.8 on 2025-11-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('EMP', 'Empleado'), ('PAS', 'Pasajero')], default='PAS', max_length=50),
        ),
    ]
