# Generated by Django 5.2.8 on 2025-11-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasajero', to=settings.AUTH_USER_MODEL),
        ),
    ]
