# Generated by Django 5.1.7 on 2025-07-21 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
