# Generated by Django 5.1.7 on 2025-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0004_boleto_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='estado',
            field=models.CharField(choices=[('emitido', 'Emitido'), ('cancelado', 'Cancelado'), ('usado', 'Usado')], max_length=50),
        ),
    ]
