# Generated by Django 5.1.7 on 2025-07-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0006_pasajero_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='usuario',
        ),
    ]
