# Generated by Django 5.1.7 on 2025-08-13 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0007_remove_pasajero_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
